version: "3"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGHOST=db
      - PGUSER=odoo
      - PGDATABASE=postgres
      - PGPASSWORD=odoo
      - PGPORT=5432
      - ADDONS_PATH=/mnt/extra-addons
      - LONGPOLLING_PORT=8072
    volumes:
      - ./custom/addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
volumes:
  odoo-db-data:
  odoo-data: